fprintf('Compiling Curie-Weiss\n');
compilestr = [
	'-output isingCW -O -IisingCW ', ...
	'-Imc -I. -I.. ', ...
	'-DDSFMT_MEXP=19937 -I../mersenne ../mersenne/dSFMT.c ' , ...
	'isingCW/magIsingCW.cpp '
	];
eval(['mex ' compilestr])

fprintf('Compiling Curie-Weiss Metropolis\n');
compilestr = [
	'-output isingCWMetropolis -O -IisingCW ', ...
	'-Imc -I. -I.. ', ...
	'-DDSFMT_MEXP=19937 -I../mersenne ../mersenne/dSFMT.c ' , ...
	'-DMETROPOLIS -IisingCW isingCW/magIsingCW.cpp '
	];
eval(['mex ' compilestr])

fprintf('Compiling Curie-Weiss sign of magnetization\n');
compilestr = [
	'-output isingCWMagsign -O -IisingCW ', ...
	'-Imc -I. -I.. ', ...
	'-DDSFMT_MEXP=19937 -I../mersenne ../mersenne/dSFMT.c ' , ...
	'-DMAGSIGN isingCW/magIsingCW.cpp '
	];
eval(['mex ' compilestr])

fprintf('Compiling Ising 1D\n');
compilestr = [
	'-output ising1D -O -Iising1D ', ...
	'-Imc -I. -I.. ', ...
	'-DDSFMT_MEXP=19937 -I../mersenne ../mersenne/dSFMT.c ' , ...
	'ising1D/magIsing1D.cpp '
	];
eval(['mex ' compilestr])

fprintf('Compiling Ising 1D systematic scan\n');
compilestr = [
	'-output ising1Dsyst -O -Iising1D ', ...
	'-Imc -I. -I.. ', ...
	'-DDSFMT_MEXP=19937 -I../mersenne ../mersenne/dSFMT.c ' , ...
	'-DSWEEP ising1D/magIsing1D.cpp '
	];
eval(['mex ' compilestr])